#ifndef GXMETAL_VERSION_H
#define GXMETAL_VERSION_H

#include <stdint.h>

#define GXMETAL_PRODUCT_VERSION_MAJOR UINT32_C(1)
#define GXMETAL_PRODUCT_VERSION_MINOR UINT32_C(9)
#define GXMETAL_PRODUCT_VERSION_PATCH UINT32_C(0)
#define GXMETAL_PRODUCT_VERSION_STRING "1.9.0"
#define GXMETAL_PRODUCT_REVISION \
    ((GXMETAL_PRODUCT_VERSION_MAJOR << 16) | \
     (GXMETAL_PRODUCT_VERSION_MINOR << 8) | \
     GXMETAL_PRODUCT_VERSION_PATCH)

#endif /* GXMETAL_VERSION_H */
